### ISSUE TITLE
Readme - incorrect version number

### ISSUE THREAD

**Issue by rayzor** [MisterJimson/animated_rotation#1]
Hi,
Thanks for an excellent simple plugin, I am using to teach Coder Dojo kids about animation in Flutter.
Readme version number appears to be incorrect. 
dependencies:
  animated_rotation: ^0.1.0 ...... fails

dependencies:
  animated_rotation: ^0.0.2 ......works

**Comment by MisterJimson** [comment]
Fixed and 1.0.0 released :)
